### ISSUE TITLE
Invalid date in index view when field value is null

### ISSUE THREAD

**Issue by aviuz80** [techouse/intl-date-time#1]
Hi.

When a Datetime field has null value in the index view it's displayed as 'Invalid date'.
In detail view it works and show '—'.

I think v-if/else is missing in `resources/js/components/Index/DateTimeField.vue`.

From:
```vue
<template>
    <span class="whitespace-no-wrap">{{ localizedDateTime }}</span>
</template>
```

To:
```vue
<template>
    <span v-if="field.value" class="whitespace-no-wrap">{{ localizedDateTime }}</span>
    <span v-else>&mdash;</span>
</template>
```

- laravel/framework  v5.7.27
- laravel/nova  v1.3.2
- techouse/intl-date-time  v1.0.4

**Comment by techouse** [comment]
Thanx for reporing it. Fixed!
