### ISSUE TITLE
Ability to add firstDayOfWeek function

### ISSUE THREAD

**Issue by tsharp-decimal** [techouse/intl-date-time#10]
On the Nova DateTime field there is an ability to change the first day of the week on the calendar.

Is it possible to introduce this functionality to IntlDateTime?

> Customizing The First Day of the Week
>
>By default, Nova's Date and DateTime fields recognize Sunday as the first day of the week (as the >United States, Canada, and Japan do). If you wish to customize this to follow the international >standard ISO 8601, you can set the firstDayOfWeek option on the field:
>
>Date::make('Birthday')->firstDayOfWeek(1);
>DateTime::make('Created At')->firstDayOfWeek(1);

**Comment by techouse** [comment]
This should theoretically be possible, however usually you'd rely on the provided [Flatpickr locale](https://github.com/flatpickr/flatpickr/blob/master/src/l10n/de.ts#L57) and [Moment locale](https://github.com/moment/moment/blob/2.24.0/locale/de.js#L68) to set this for you automatically.

**Comment by techouse** [comment]
[v.1.2.5](https://github.com/techouse/intl-date-time/blob/master/resources/js/components/IntlDateTimePicker.vue#L101) now features the option to override `firstDayOfWeek` just like you would in the native Nova `Date` and/or `DateTime` field.
