### ISSUE TITLE
Set initial year value

### ISSUE THREAD

**Issue by iventru** [techouse/intl-date-time#11]
I make a museum site, and many exhibits date back to an average 1990 year. Every time flipping the date from 2019 to 1990 is not convenient.
Is it possible to set the initial year? (but not withMeta -> value).

**Comment by techouse** [comment]
You do **not** have to flip the calendar back 30 years or so every time you wanna go back in the 90's 🤣 In [v1.2.5](https://github.com/techouse/intl-date-time/commit/a19a6b0a8dc88ad207cd8a1ed3cea689793581ee#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R16) I updated flatpickr to [v4.6.1](https://github.com/flatpickr/flatpickr/releases/tag/v4.6.0) which [features a more powerful year and month selector](https://github.com/flatpickr/flatpickr/issues/269). You should've been able to select a past year from a dropdown or even type it into it. Check the gif example below:

![back in time](http://i67.tinypic.com/294tle1.gif)

**Comment by iventru** [comment]
Hmm, really, did not notice this. Thanks! )

**Comment by techouse** [comment]
Cool 💃
