### ISSUE TITLE
Set min and max range for date-time gui selectable?

### ISSUE THREAD

**Issue by iventru** [techouse/intl-date-time#12]
Is it possible to set a dialed date that can be selected in the calendar? 
(Is not a validation) 
I mean that they physically could not be selected in the calendar grid.

**Comment by techouse** [comment]
Should be [possible](https://flatpickr.js.org/examples/#mindate-and-maxdate). Wanna make a PR?

**Comment by techouse** [comment]
Implemented in [v1.3.1](https://github.com/techouse/intl-date-time/commit/e5606e374c6611ac3c7faca2bbc77f95f9a37f3a)
