### ISSUE TITLE
Make userTimezone configurable for DateTimeField.vue

### ISSUE THREAD

**Issue by gabrielesbaiz** [techouse/intl-date-time#14]
Great package! Just a suggestion.

It would be useful to have a configurable option to show/hide userTimezone on DateTimeField.vue on line 21.

**Comment by techouse** [comment]
Possible. Wanna make a pull request?

**Comment by techouse** [comment]
[Implemented](https://github.com/techouse/intl-date-time/commit/c5285f718ca9e17854d96dc58f07ddb1042c9e51).
