### ISSUE TITLE
Wrong date

### ISSUE THREAD

**Issue by num3r06** [techouse/intl-date-time#15]
Hi, great job  
but if i select a date from datepicker when save resource the saved date it's a day before the selected day.
The locale it's 'it'

**Comment by techouse** [comment]
Sounds to me like you have a timezone issue. Check your `config/app.php` at line `70`. Is it set to `'timezone' => 'Europe/Rome'` or is it the default `UTC`? If so that would explain your error.

**Comment by num3r06** [comment]
Yes!
I fix timezone and all work fine
Thx

**Comment by fpcimmino** [comment]
Hi, don't work for me. I forgot something?
