### ISSUE TITLE
timeFormat mandatory

### ISSUE THREAD

**Issue by fnmancinelli** [techouse/intl-date-time#16]
Hi, I use this Nova package with timestamp field in the database.
In the readme file, you explain "timeFormat - OPTIONAL - Set a time format. If you do not provide it the module will automatically use HH:mm:ss.", but isn't true.
Because if I've a datetime field in the database, and not set the timeFormat, the time not showing at all.
If I set timeFormat, it's all right.
`DateTime::make('expires_at')
                ->minDate(Carbon::today())
                ->timeFormat('HH:mm:ss')`

Thanks

**Comment by techouse** [comment]
Hi and thank you for your report. You have a keen eye for detail 😇 Fixed.
