### ISSUE TITLE
How use in Date Filters?

### ISSUE THREAD

**Issue by cbmaster-net** [techouse/intl-date-time#18]
How use Techouse\IntlDateTime\IntlDateTime in Date Filters? 
For example https://nova.laravel.com/docs/2.0/filters/defining-filters.html#date-filters

**Comment by techouse** [comment]
Hi! To be honest I have no idea. If I had more free time on my hands I would look into it but unfortunately, that is not the case, so if anyone is up to the challenge, by all means.

**Comment by oleksandr-roskovynskyi** [comment]
I'll try to rewrite the components...

**Comment by techouse** [comment]
> I'll try to rewrite the components...

OK. 🚀

However, this does not look like a simple re-write but more like different package altogether. This is a [Field](https://nova.laravel.com/docs/1.0/resources/fields.html#datetime-field) and what you're asking for is a [Filter](https://nova.laravel.com/docs/2.0/customization/filters.html#filters).

P.S.: I have just updated the package's dependencies. Be sure to fork this one as it has almost 2 months worth of updated packages in it. 😇

**Comment by oleksandr-roskovynskyi** [comment]
I'll try to rewrite the  Filter component in future (that's what I meant)
