### ISSUE TITLE
Feature Request: Add Mask to input.

### ISSUE THREAD

**Issue by wemersonrv** [techouse/intl-date-time#2]
Hi. Great file.

Please add maskinput feature to be used with localization/format.

Example: If define a **pt** localization, uses the slash(`/`) as mask element... if use `DD/MM/YYYY` format, uses the slash too... if uses time, uses `:` too... point, dash, etc... of couse, depending on the display formatting.

**Comment by techouse** [comment]
Hello @wemersonrv 

You can use your own custom date format the same as you would with the standard [Laravel Nova `DateTime` field](https://nova.laravel.com/docs/1.0/resources/fields.html#datetime-field)
```php
Date::make('Created At')->format('DD MMM YYYY')
```

So I think this issue is already covered unless I understand you incorrectly.

**Comment by wemersonrv** [comment]
> Hello @wemersonrv
> 
> You can use your own custom date format the same as you would with the standard [Laravel Nova `DateTime` field](https://nova.laravel.com/docs/1.0/resources/fields.html#datetime-field)
> 
> ```
> Date::make('Created At')->format('DD MMM YYYY')
> ```
> 
> So I think this issue is already covered unless I understand you incorrectly.

Nope.. it's not covered. Formatting the date, will only define it's format, not force typing with the mask. My suggestion is to add the mask chars automatically when typing. So users cannot type these chars. For exemple:

Brazilian date DD/MM/YYYY --> ##/##/#### user type 14051973 and field shows 14/05/1973
Brazilian time HH:mm:ss --> ##:##:## (11:59:38)
Brazilian Datetime DD/MM/YYYY HH:mm:ss --> #### ##:##:## (14/05/1973 11:59:38)
US Datetime:  MM-DD-YYYY hh:mm:ss --> ##-##-#### ##:##:## (05-14-1973 11:59:38)
MySQL datetime:  YYYY-MM-DD hh:mm:ss --> ####-##-## ##:##:## (1973-05-14 11:59:38)

Or any other mask chars: - /.

**Comment by techouse** [comment]
Aha I see. Will look into it when I have more time on my hands. You are of course very welcome to make a PR :)

**Comment by techouse** [comment]
Added in [v1.1.0](https://github.com/techouse/intl-date-time/commit/4e8c4837e9d21e0d1a0bc96d0f9bd5e91287573f). It uses [vue-the-mask](http://github.com/vuejs-tips/vue-the-mask) to do the masking.
