### ISSUE TITLE
Use just the date

### ISSUE THREAD

**Issue by henryavila** [techouse/intl-date-time#22]
Hi. Is possible to use just for date, and don't  show the time (in view and picker)? use with a Date DB column?

**Comment by techouse** [comment]
Yes.

**Comment by Sonicelo** [comment]
Its not that simple, because the timezone gets changes in the background, it sometimes changes the date for a day. Any fix for this?

**Comment by techouse** [comment]
> Its not that simple, because the timezone gets changes in the background, it sometimes changes the date for a day. Any fix for this?

see #25
