### ISSUE TITLE
Date not showing and saving properly

### ISSUE THREAD

**Issue by jahid56** [techouse/intl-date-time#26]
Hello,
I have an issue in my project. My date is not showing and saving properly. Also when I check date it shows error `The Booking Closing Date must be in the format dd/MM/yyyy`. It also saving wrong data. For example if my date is 20-04-2020 then it saves 31-09-2031. I do't know where the problem exists.
Here is my Code
`DateTime::make('Booking Closing Date', 'booking_closing_at')
		->rules('required')
		->dateFormat('DD-MM-YYYY')
		->placeholder('DD-MM-YYYY'),`

**Comment by techouse** [comment]
Hey!

I'll need some more info in order to replicate the bug.

Can you maybe share your config and/or create a GitHub repo?

Also, what's your locale?

**Comment by techouse** [comment]
@jahid56 check the reply here https://github.com/techouse/intl-date-time/issues/25#issuecomment-611997915

**Comment by techouse** [comment]
bump

**Comment by techouse** [comment]
Duplicate #25
