### ISSUE TITLE
border-danger is missing when validation fails

### ISSUE THREAD

**Issue by hcancelik** [techouse/intl-date-time#32]
Thanks for the package. 

It looks like `border-danger` class is missing when the field validation fails. 

![image](https://user-images.githubusercontent.com/5788410/87342848-9b33a800-c554-11ea-94b8-e2d50044cff5.png)

**Comment by techouse** [comment]
Hmm, sorry but I can't reproduce your issue. I correctly get the `border-danger` class.

<img width="2032" alt="Screenshot 2020-07-14 at 19 31 48" src="https://user-images.githubusercontent.com/1174328/87463093-cd9edd00-c608-11ea-8b4c-bc1cddf680cb.png">

**Comment by hcancelik** [comment]
@techouse  

I have tested again on a brand new Nova installation (v.3.7.1) and still not working. 
Also noticed that `->required()` doesn't even trigger any errors.

It looks like you have a custom validation that triggers onBlur to check the date format. However, the validation rules from Nova doesn't get triggered(`->required()`) or missing the class I mentioned.

**Comment by techouse** [comment]
Fixed.

This wasn't so much a border or class issue. I had somehow forgotten to even use the required attribute altogether. 🤷‍♂️ 

https://github.com/techouse/intl-date-time/blob/master/resources/js/components/IntlDateTimePicker.vue#L11

**Comment by hcancelik** [comment]
~~@techouse Thanks for the responses. I just updated to v1.5.10 and all IntDateTime fields are now invisible :(~~

Never mind. Had to do hard reload.

**Comment by techouse** [comment]
🤣 glad it works 👍
