### ISSUE TITLE
Field not showing

### ISSUE THREAD

**Issue by MB116** [techouse/intl-date-time#35]
Hi, I ran into a problem after updating to 1.6.1.
After the update, the following scripts and styles stopped loading, 

vendors~detail-intl-date-time~form-intl-date-time~index-intl-date-time.js | 404 | 
vendors~form-intl-date-time.js | 404 |
form-intl-date-time.css | 404 |
form-intl-date-time.js | 404 |,

could you help?

**Comment by techouse** [comment]
Just checked and it works just fine for me.

Can you provide some more detail?

**Comment by henryavila** [comment]
I was facing this same problem. The strange is that in local environment (macOS) it works. But on Homologation (Laravel Forge/DigitalOcean/Ubuntu 18.04) it don't work. The field simple don`t display in forms (create/edit).

In my case it back to work when I opened the Dev tolls and disabled the cache.

**Comment by Jon78** [comment]
We're seeing similar issues on our staging environment. When a request comes in for either /nova-vendor/intl-date-time/js/index-intl-date-time.js or /nova-vendor/intl-date-time/js/vendors~detail-intl-date-time~form-intl-date-time~index-intl-date-time.js, only one of our three backends sends a proper 200 response. The other two give a 302 redirect to our login screen. So I think something went wrong when deploying, but I can't figure out what 😕️

**Comment by techouse** [comment]
Maybe the new Nova is causing it. I have no idea when I'll be able to work on this again since I'm occupied by work almost 24/7. If anyone of you has the time, please be my guest.

**Comment by Jon78** [comment]
False alarm in our case. Upgrading in production went fine. Maybe the assets got cached or something.

**Comment by kayacekovic** [comment]
I have the same issue. My staging and production servers in the same machine. In my production, package assets getting 404 error but when i clicked the assets, browser show the files. But there is no problem with my staging app. I try to clear cache in laravel app and Cloudflare.

**Comment by remkobrenters** [comment]
For who ends up here: This is probably due to your Nginx setup resulting in a 404 for the route based link to the dist files (js & css). Solutions are either adding a copy of the package files to your projects public folder (we added them to our Laravel mix to replicate them automatically on builds) or adding symlinks from public/nova-vendor/intl-date-time/js & ublic/nova-vendor/intl-date-time/css to the correct folders in the vendor map.

**Comment by abishekrsrikaanth** [comment]
Are there any better resolutions to this to get this working on Forge than symlinking it?
