### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by pit07** [techouse/intl-date-time#37]
Hi!
I have to put all my dates on FR format.
I try to install intl-date-time, but:

PS D:\_CLIENTS\Kidilist\www> composer require techouse/intl-date-time
Using version ^1.6 for techouse/intl-date-time
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing techouse/intl-date-time (v1.6.2): Downloading (100%)
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   ErrorException 

  rename(D:\_CLIENTS\Kidilist\www\bootstrap\cache\pac838A.tmp,D:\_CLIENTS\Kidilist\www\bootstrap\cache\packages.php): Accès refusé. (code: 5)

  at D:\_CLIENTS\Kidilist\www\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:209
    205▕         chmod($tempPath, 0777 - umask());
    206▕
    207▕         file_put_contents($tempPath, $content);
    208▕
  ➜ 209▕         rename($tempPath, $path);
    210▕     }
    211▕
    212▕     /**
    213▕      * Prepend to a file.

  1   D:\_CLIENTS\Kidilist\www\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:209
      rename("D:\_CLIENTS\Kidilist\www\bootstrap\cache\pac838A.tmp", "D:\_CLIENTS\Kidilist\www\bootstrap\cache\packages.php")

  2   D:\_CLIENTS\Kidilist\www\vendor\laravel\framework\src\Illuminate\Foundation\PackageManifest.php:181
      Illuminate\Filesystem\Filesystem::replace("D:\_CLIENTS\Kidilist\www\bootstrap\cache\packages.php", "<?php return array (
  'coderello/laravel-nova-lang' =>
  array (
    'providers' =>
    array (
      0 => 'Coderello\\LaravelNovaLang\\Providers\\LaravelNovaLangServiceProvider',
    ),
  ),
  'facade/ignition' =>
  array (
    'providers' =>
    array (
      0 => 'Facade\\Ignition\\IgnitionServiceProvider',
    ),
    'aliases' =>
    array (
      'Flare' => 'Facade\\Ignition\\Facades\\Flare',
    ),
  ),
  'fideloper/proxy' =>
  array (
    'providers' =>
    array (
      0 => 'Fideloper\\Proxy\\TrustedProxyServiceProvider',
    ),
  ),
  'fruitcake/laravel-cors' =>
  array (
    'providers' =>
    array (
      0 => 'Fruitcake\\Cors\\CorsServiceProvider',
    ),
  ),
  'laravel/nova' =>
  array (
    'providers' =>
    array (
      0 => 'Laravel\\Nova\\NovaCoreServiceProvider',
    ),
    'aliases' =>
    array (
      'Nova' => 'Laravel\\Nova\\Nova',
    ),
  ),
  'laravel/tinker' =>
  array (
    'providers' =>
    array (
      0 => 'Laravel\\Tinker\\TinkerServiceProvider',
    ),
  ),
  'laravel/ui' =>
  array (
    'providers' =>
    array (
      0 => 'Laravel\\Ui\\UiServiceProvider',
    ),
  ),
  'nesbot/carbon' =>
  array (
    'providers' =>
    array (
      0 => 'Carbon\\Laravel\\ServiceProvider',
    ),
  ),
  'nunomaduro/collision' =>
  array (
    'providers' =>
    array (
      0 => 'NunoMaduro\\Collision\\Adapters\\Laravel\\CollisionServiceProvider',
    ),
  ),
  'techouse/intl-date-time' =>
  array (
    'providers' =>
    array (
      0 => 'Techouse\\IntlDateTime\\FieldServiceProvider',
    ),
  ),
  'therobfonz/laravel-mandrill-driver' =>
  array (
    'providers' =>
    array (
      0 => 'LaravelMandrill\\MandrillServiceProvider',
    ),
  ),
);")
**Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
Installation failed, reverting ./composer.json to its original content.**

Any ideas ?

Thanks a lot!

**Comment by techouse** [comment]
Looks like you can't write to your files for some reason. Maybe another process is using it and then Windows locks it up. Anyhow, closing this ticket.
