### ISSUE TITLE
Help text not working

### ISSUE THREAD

**Issue by baaskoen** [techouse/intl-date-time#39]
When using the following field:

```
IntlDateTime::make(__('Label'), 'field_name')
                ->hideUserTimeZone()
                ->help(__('Some help text'))
                ->withTimeShort()
                ->minDate(now()->addDay())
                ->rules('required', 'date'),
```
The help text is not shown in the form.

In `Vue Dev Tools` I can see that the IntlDateTimePicker component has the property `showHelpText` set to `true`, but it seems this property is not (properly) passed to the `default-field` of Nova.

**Comment by techouse** [comment]
Fixed in https://github.com/techouse/intl-date-time/pull/42
