### ISSUE TITLE
When try to submit empty dates, it sends Invalid Date

### ISSUE THREAD

**Issue by wemersonrv** [techouse/intl-date-time#4]
Hello.

I found an issue with nullable datetime columns. When send empty values, it sends **Invalid Date** But need to store a valid date or **NULL**

See image below:

![intl-date-time](https://user-images.githubusercontent.com/2028673/57962979-436bc380-78f4-11e9-8cc6-d402b3e82573.png)

**Comment by techouse** [comment]
Will look into it.

**Comment by techouse** [comment]
Fixed in [v1.1.1](https://github.com/techouse/intl-date-time/releases/tag/v1.1.1)! Thanx for the info :)
