### ISSUE TITLE
Please make submit action obey date/time format to be a validd date

### ISSUE THREAD

**Issue by wemersonrv** [techouse/intl-date-time#5]
Please make submit action obey date/time format to be a validd date

Example: User do not fill entire date format, just inform a part of date... but InlDateTime field accepts as dai **** from current month. If i'm forcing a format is because i want this pattern to be filled.

```php
IntlDateTime::make('Birthdate', 'birthdate')
            ->rules('required', 'date')
            ->dateFormat('DD/MM/YYYY')
            ->hideFromIndex(),
```

![intl](https://user-images.githubusercontent.com/2028673/58024448-94440d80-7ae8-11e9-9310-9a116347a32d.png)

Other stuff: Make component accept only `date`, if i'm using a format `DD/MM/YYYY` or something like that don't need to complement it with `00:00:00`

**Comment by techouse** [comment]
I am pretty sure this should not display any time if you don’t specify a `timeFormat`.

Please elaborate a bit more. How is your database schema set up? Are you using a date field or datetime field in MySQL?

The module itself is an extension of the Nova DateTime field, hence the name.

**Comment by wemersonrv** [comment]
Yep. Not show... but send it with `00:00:00` to save...

**Comment by techouse** [comment]
But if you would simply store the date in a MySQL [`date`](https://dev.mysql.com/doc/refman/8.0/en/datetime.html) field instead of `datetime` it should not store any time, am I right?

user interface
![ui](http://i64.tinypic.com/50jocz.png)
MySQL schema
![database_schema](http://i68.tinypic.com/2sbtizt.png)
stored data
![stored_data](http://i67.tinypic.com/2irt01f.png)

**Comment by wemersonrv** [comment]
I think so.

**Comment by wemersonrv** [comment]
But, about to abey the format? I think it's obvious that it's better to obey the format before consider a valid date... inform only a day or month is not enough to fill entire date

**Comment by techouse** [comment]
So if I understand you correctly you would like some sort of validation on the client side? In general the user would pick the date from the dropdown datepicker which is shown once the field is clicked.

If you want validation then please close this issue and make a new to make all conversation less confusing. 😇
