### ISSUE TITLE
Adding new french translation

### ISSUE THREAD

**Issue by airdev-web** [techouse/intl-date-time#50]
Hello !

I noticed that the 'fr' translation is not quite complete. Where can I add the missing translations?

Hello from Belgium!

**Comment by techouse** [comment]
The translations are automatic and pulled from MomentJS, so there are no manual translations. You'd have to take it up to MomentJS to update their locale files I guess.

**Comment by techouse** [comment]
In case you mean the error/validation messages, those are from VeeValidate. Again all exctracted.
