### ISSUE TITLE
Closing Modal when selecting next Month since Nova 3.30

### ISSUE THREAD

**Issue by skywalker666** [techouse/intl-date-time#55]
I'm using the component in a Nova-Action that shows as a modal. The date picker get's triggered all right but when I select the right arrow for _next month_ the action modal closes (the picker stays). This used to work and seems to be introduced by Nova 3.30 which states in it's changelog: 

> Fixed issue with clicking away from a modal when using an iPad.

But I'm not so sure about that. It used to work with Nova 3.29 just fine. Switching to the original date field Nova brings along, also works :-(

**Comment by techouse** [comment]
I don't have time to actively develop this anymore to support more recent Nova versions. Feel free to make a PR.
