### ISSUE TITLE
Please add client side validation

### ISSUE THREAD

**Issue by wemersonrv** [techouse/intl-date-time#7]
As you told me in this issue: #5 i am opening this to request a feature to client side validation in a specific case... See the image below:

![intl](https://user-images.githubusercontent.com/2028673/58024448-94440d80-7ae8-11e9-9310-9a116347a32d.png)

User add only `05` and Field assumes current year and month and make a validad date from `2019-05-05 00:00:00`. 

Many times, when putting far away dates (as my birth date lol)... is boring to use visual date component to get back until 1973 or older dates and i's better manually type the date. If user add a invalid value like `05/0` it will result in a invalid date, fine in this case... but if user add a part of date like only `5`  will be accepted as a valid date but in my opinion is not valid.

**Comment by techouse** [comment]
Client side validation added in [v1.2.0](https://github.com/techouse/intl-date-time/commit/bffeee4e99604ce2b7b26d689b98790818a3bac7)
